name: Node CI

on: [pull_request]

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Determine if Dependabot
        id: dependabot
        run: echo "is_dependabot=$(echo ${{ github.actor }} | grep -q 'dependabot' && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          if [ "${{ steps.dependabot.outputs.is_dependabot }}" = "true" ]; then
            bun i
          else
            bun i --frozen-lockfile
          fi

      - name: Build
        run: bun run build
      
      - name: Test
        run: bun test
